// home
export const GET_MOVIE_REVENUES = 'GET_MOVIE_REVENUES';
export const GET_CINEMA_REVENUES = 'GET_CINEMA_REVENUES';
export const GET_CINEMA_LINE_REVENUES = 'GET_CINEMA_LINE_REVENUES';

// schedules
export const GET_MOVIE_SCHEDULES = 'GET_MOVIE_SCHEDULES';

// news
export const GET_NEWS_DATA = 'GET_NEWS_DATA';
