// home
export const GET_MOVIE_REVENUES = 'GET_MOVIE_REVENUES';
export const GET_CINEMA_REVENUES = 'GET_CINEMA_REVENUES';
export const GET_CINEMA_LINE_REVENUES = 'GET_CINEMA_LINE_REVENUES';

// schedules
export const GET_MOVIE_SCHEDULES = 'GET_MOVIE_SCHEDULES';
export const GET_TYPE = 'GET_TYPE';

// news
export const GET_NEWS_DATA = 'GET_NEWS_DATA';

// common 
export const GET_DATE = 'GET_DATE';

// production
export const GET_ANALYSIS_DETAILS = 'GET_ANALYSIS_DETAILS';
export const GET_CELEBRITIES_RANKING = 'GET_CELEBRITIES_RANKING';
export const GET_FILM_RANKING = 'GET_FILM_RANKING';
